upload:
  path: /home/avada/web/slj.demodev.cc/projects/My-house24_Rudiuk_Lesyk/uploads

#AWS
aws:
  accessKey: ${awsAccessKey}
  secretAccessKey: ${awsSecretAccessKey}
  endpoint: https://testbucket-my-house.s3.us-east-2.amazonaws.com/
  bucketName: testbucket-my-house

#SendGrid
secret-key: ${sendgridSecretKey}
sender: ${sendgridSender}
#ReCaptcha
google:
  recaptcha:
    key:
      site: ${recaptchaSiteKey}
      secret: ${recaptchaSecretKey}

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/my_house24
    username: ${MYSQL_USER:root}
    password: ${databasePassword}
  jpa:
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  servlet:
    context-path: /my-house24-rudiuk-lesyk
  error:
    whitelabel:
      enabled: false
  tomcat:
    max-swallow-size: 100000000
    max-http-form-post-size: 100000000